### ISSUE TITLE
One layout file entry creating multiple pages

### ISSUE THREAD

**Issue by ElliotPak** [ElliotPak/Snippetter#10]
This would allow building multiple pages from one layout entry.

A sample layout entry might look like this:

```yaml
- type: multi-macro
  macro-name: title-page
  values-from-file: entries/some-file.yaml
  output-file-parameter: filename
```

This would execute the "title-page" macro multiple times, once using each entry in `entries/somefile.yaml`, and saving a separate file based on each.

Not quite sure how to represent or generate the output filename in plain YAML. In all likelyhood, that will have to be defined in Haskell. I'll likely allow the user to specify `Params -> Text` functions to determine it, and define some defaults, but how this will be done for now is not known.
