### ISSUE TITLE
SubMacro evaluates files in reverse order

### ISSUE THREAD

**Issue by ElliotPak** [ElliotPak/Snippetter#2]
What it says on the title. Say you're adding the results of a `SubMacro`, and the parameter file has the following:

```yaml
- title: Thing A
  desc: Desc A
- title: Thing B
  desc: Desc B
```

When the `Doc` is evaluated, the resulting string will have Thing B before Thing A.
