### ISSUE TITLE
Basic macros defined in YAML

### ISSUE THREAD

**Issue by ElliotPak** [ElliotPak/Snippetter#8]
While an intended strength of Snippetter is that all operations are defined in Haskell for more extensibility, the fact that it has to be written in Haskell is a hurdle for some people. Ideally, it should be possible to define a macro in a YAML file like so:

```yaml
- macro-name: example
  required-params:
    - title: string
    - desc: string
  steps:
    - add:
        snippet: index.html
    - replace: %NAME%
      with: $title$
    - replace: %DESCRIPTION%
      with: $desc$
```

Within the YAML file, the required parameters would be defined, and then any content string containing a parameter's name between dollar signs would replace those dollar signs and the included text with the parameter's value.

Also note that these YAML files could be parsed to create macros, and then added to the user's provided `MacroMap`.

This is quite far off in the future.
